In [1]:
# Initial imports
import pandas as pd
import numpy as np
#  Import and read the county_data.csv.
cleaned_county_df = pd.read_csv("county_data_cleaned.csv")
cleaned_county_df.head()

,county,state,votes16_Donald_Trump,votes16_Hillary_Clinton,total_votes16,total_votes20,votes20_Donald_Trump,votes20_Joe_Biden,cases,deaths,TotalPop,Poverty,Income,IncomePerCap,IncomePerCapErr
0,Abbeville,SC,6742.0,3712.0,10724.0,12433.0,8215.0,4101.0,805.0,17.0,24788.0,22.7,35254.0,19234.0,799.0
1,Acadia,LA,21159.0,5638.0,27386.0,28425.0,22596.0,5443.0,3182.0,102.0,62607.0,21.5,40492.0,21591.0,1002.0
2,Accomack,VA,8582.0,6737.0,15755.0,16938.0,9172.0,7578.0,1227.0,19.0,32840.0,19.8,42260.0,24266.0,1564.0
3,Ada,ID,93748.0,75676.0,195587.0,259389.0,130699.0,120539.0,17451.0,181.0,435117.0,11.8,60151.0,31642.0,725.0
4,Adair,IA,2456.0,1127.0,3759.0,4183.0,2917.0,1197.0,222.0,1.0,7192.0,9.5,49477.0,28861.0,2055.0

In [2]:
# Seperate X features from Y features
y = cleaned_county_df["total_votes20"]
X = cleaned_county_df.drop(columns=["total_votes20", "county", "state"])

In [3]:
# Split our data into training and testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                   )
X_train.shape

(2285, 12)

In [4]:
# Create a Logistic Regression Model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=1000,
                                random_state=1)

In [5]:
#Fit (train) or model using the training data
classifier.fit(X_train, y_train)

/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(max_iter=1000, random_state=1)

In [6]:
# Make predictions
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction    Actual
0       7926.0   10337.0
1      11983.0   15531.0
2      65860.0   52053.0
3      10309.0   14110.0
4       7881.0    8247.0
5     376915.0  160855.0
6      10703.0    8555.0
7      30441.0   15985.0
8      16341.0   24120.0
9      44935.0   25005.0
10      6611.0    6161.0
11      7509.0    5991.0
12      2672.0    2881.0
13      8903.0    5575.0
14      1172.0    1014.0
15     82244.0   77563.0
16    127162.0   92609.0
17    566192.0  629804.0
18     10066.0   11698.0
19     17748.0   18488.0

In [7]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.0013123359580052493